# Generated by Django 4.0.5 on 2022-06-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name_shop', models.CharField(max_length=30)),
                ('id_shop', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vendor_code', models.CharField(max_length=25, unique=True)),
                ('price', models.CharField(max_length=20)),
                ('availability', models.CharField(max_length=30)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.sellers')),
            ],
            options={
                'verbose_name': 'Good',
            },
        ),
    ]
