# Generated by Django 4.0.5 on 2022-06-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='id_shop',
            new_name='id_partner',
        ),
    ]
